<?php
# This file was automatically generated by the MediaWiki 1.31.0-alpha
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "@jehovahsays";
$wgMetaNamespace = "Project";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/blackhole/wiki";

## The protocol and server name to use in fully-qualified URLs
$wgServerName = 'jehovahsays.net';
$wgServer = "http://127.0.0.1";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$wgResourceBasePath/resources/assets/mediawiki.png";

## UPO means: this is also a user preference option
$wgEnableEmail = false;
$wgEnableUserEmail = false; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = false;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "";
$wgDBname = "";
$wgDBuser = "";
$wgDBpassword = "";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = false;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "C.UTF-8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "C:\\Program Files\\Git\\usr\\bin\\diff3.exe";
$wgDiff = "C:\\Program Files\\Git\\usr\\bin\\diff.exe";
$wgCollapsibleVectorFeatures['collapsiblenav']['global'] = true;
//$wgSecureLogin = false;
$wgCookieHttpOnly = true;
$wgCookieSecure = 'detect';
//$wgHiddenPrefs[] = 'realname';
$wgUrlProtocols = array(
   'bitcoin:'
);
//$wgRawHtml = false;
//$wgUseRCPatrol= false;
$wgShowIPinHeader = false;
$wgPutIPinRC = false;
$wgDisableAnonTalk = false;
//$wgResourceLoader = false;
$wgBreakFrames = true;
$wgApiFrameOptions = 'DENY';
$wgEditPageFrameOptions = 'DENY';
$wgMangleFlashPolicy = true;
$wgValidateAllHtml  = true;
//$wgDefaultUserOptions['skin'] = false;
//$wgHiddenPrefs[] = 'skin';
//$wgLoadScript = false;
//$wgStylePath = false;
//$wgDBWindowsAuthentication = false;
$wgAmericanDates = true;
$wgUseCopyrightUpload = true;
//$wgWhitelistRead =  array ( "Main_Page", "Main_Page&printable=yes", "Project:Privacy_policy", "Project:General_disclaimer", "Project:About", "Special:Userlogin", "Special:UserLogin&printable=yes", "Special:CreateAccount", "Special:CreateAccount&printable=yes", "Special:RecentChanges", "Special:RecentChanges&printable=yes", "Special:Search", "Special:Search&printable=yes", "Special:PasswordReset", "Special:PasswordReset&printable=yes", "Special:SpecialPages", "Special:SpecialPages&printable=yes" );

# for everyone
$wgGroupPermissions['*']['read'] = true;
$wgGroupPermissions['*']['createaccount'] = true;
$wgGroupPermissions['*']['view'] = true;
$wgGroupPermissions['*']['edit'] = false;

# for users
$wgGroupPermissions['user']['read'] = true;
$wgGroupPermissions['user']['createaccount'] = false;
$wgGroupPermissions['user']['view'] = true;
$wgGroupPermissions['user']['edit'] = true;

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
wfLoadSkin( 'Vector' );
$wgVectorUseSimpleSearch = true;
$wgVectorUseIconWatch = true;
$wgVectorResponsive = true;
$wgDefaultSkin = "vector";

# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtensions('ExtensionName');
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled
wfLoadExtension( 'Cite' );
wfLoadExtension( 'CiteThisPage' );
wfLoadExtension( 'ConfirmEdit' );
wfLoadExtension( 'Gadgets' );
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'Interwiki' );
wfLoadExtension( 'LocalisationUpdate' );
wfLoadExtension( 'Nuke' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'Poem' );
wfLoadExtension( 'Renameuser' );
wfLoadExtension( 'SpamBlacklist' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'TitleBlacklist' );
wfLoadExtension( 'WikiEditor' );
$wgHiddenPrefs[] = 'usebetatoolbar';
$wgDefaultUserOptions['usebetatoolbar'] = 1;
require_once "$IP/extensions/Jehovahsays/Jehovahsays.php";
$wgSecurity = '
<style>
p.dotted {border-style: dotted;}
p.dashed {border-style: dashed;}
p.solid {border-style: solid;}
p.double {border-style: double;}
p.groove {border-style: groove;}
p.ridge {border-style: ridge;}
p.inset {border-style: inset;}
p.outset {border-style: outset;}
p.none {border-style: none;}
p.hidden {border-style: hidden;}
p.mix {border-style: dotted dashed solid double;}
</style>
';

# You can add <noscript> within $wgBottomSecurity = ''; to lockdown wiki
$wgBottomSecurity = '
<a rel="nofollow" style="display:none;" href="/blackhole/" title="Do NOT follow this link or you will be temporarily banned from the site! The blackhole.dat file can lift ban"><img src="/blackhole/__utm.gif" alt="" /></a>
';

# End of automatically generated settings.
# Add more configuration options below.

